version: "3.9"
services:
  hp_torpus:
    depends_on:
      - wp_video
      - wp_audio
    ports:
    - 80:80
    - 443:443
    - 5037:5037
    build:
      #network: host
      context: .
      dockerfile: ./ipfs.dockerfile
    volumes:
      - ./tor:/root/tor
      - ./hidden_service:/root/hidden_service
      - ./tor:/usr/local/etc/tor/
      - ./torplus_ssl:/etc/ssl/torplus/
      - ./geodata:/root/geodata
    environment:
    - PP_ENV=prod
    - seed=SA7WPOPXXH4HCWEJLVBTZ3MR737LELODG5O26FGGVD75IOIQY7H6UV3Q
    - role=hs_client
    - nickname=cponion2
    - UseTestApi=false
    entrypoint: ["/start.sh"]
    #entrypoint: ["bash","-c", "while true; do echo step; sleep 2; done"]
  # hp_only:
  #     ports:
  #       - 80:80
  #       - 443:443
  #     depends_on:
  #       - wp_video
  #       - wp_audio
  #     build:
  #       network: host
  #       context: .
  #       dockerfile: ./ipfs.dockerfile
  #     volumes:
  #       - ./tor:/root/tor
  #       - ./tor:/usr/local/etc/tor/
  #       - ./torplus_ssl:/etc/ssl/torplus/
  #     environment:
  #     - PP_ENV=prod
  #     - seed=SC3AP557F22T43LT2APIXQPEW2IAQ2IOVKRG4PVV6KUTFRBMT46NDFDR
  #     - role=hs_client
  #     entrypoint: ["/haproxy-docker-entrypoint.sh"]
  db_audio:
    image: mysql:5.7
    volumes:
    - ./audio/db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootps
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  wp_audio:
    depends_on:
      - db_audio
    ports: 
      - 8092:8092
    image: wordpress:latest
    volumes:
      - ./audio/wp:/var/www/html
      - ./audio/backup:/var/www/html/wp-content/updraft
    restart: always
    environment:
      WORDPRESS_DB_HOST: db_audio:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
  db_video:
      image: mysql:5.7
      volumes:
      - ./video/db:/var/lib/mysql
      restart: always
      environment:
          MYSQL_ROOT_PASSWORD: rootps
          MYSQL_DATABASE: wordpress
          MYSQL_USER: wordpress
          MYSQL_PASSWORD: wordpress
  download:
    image: nginx
    volumes: 
    - ./download_site:/usr/share/nginx/html
  demovideo:
    image: nginx
    ports: 
      - 8083:80
    volumes: 
    - ./demovideo:/usr/share/nginx/html
  wiki:
    build:
      context: .
      dockerfile: ./wiki.dockerfile
    volumes:
      - ./wiki:/xowa
  wp_video:
      depends_on:
      - db_video
      ports: 
      - 8091:8091
      image: wordpress:latest
      volumes:
           - ./video/wp:/var/www/html
           - ./video/backup:/var/www/html/wp-content/updraft
      restart: always
      environment:
          WORDPRESS_DB_HOST: db_video:3306
          WORDPRESS_DB_USER: wordpress
          WORDPRESS_DB_PASSWORD: wordpress
          WORDPRESS_DB_NAME: wordpress


# mysql --user="$MYSQL_USER" --password="$MYSQL_PASSWORD" --database="$MYSQL_DATABASE" --execute "UPDATE wp_options SET option_value = 'http://torplus.videotpdemo.com/' WHERE option_name = 'home' OR option_name = 'siteurl';"
# mysql --user="$MYSQL_USER" --password="$MYSQL_PASSWORD" --database="$MYSQL_DATABASE" --execute "UPDATE wp_options SET option_value = 'http://torplus.podcasttpdemo.com/' WHERE option_name = 'home' OR option_name = 'siteurl';"
