version: "3.9"
services:
  hp_torpus:
    depends_on:
      - wiki
    ports:
    - 80:80
    - 443:443 # you can comment
    - 5037:5037
    image: torplusdev/production:ipfs_haproxy-latest 
    volumes:
      - ./tor:/root/tor
      - ./hidden_service:/root/hidden_service
      - ./tor:/usr/local/etc/tor/
      - ./ssl:/etc/ssl/torplus/
    environment:
      - http_address=wiki:80
  wiki:
    build:
      context: .
      dockerfile: ./wiki.dockerfile
